# Generated by Django 4.0.6 on 2022-07-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(max_length=20, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'competency',
                'verbose_name_plural': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'expertise',
                'verbose_name_plural': 'expertise',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('areas_of_expertise', models.ManyToManyField(blank=True, to='core.expertise')),
                ('competencies', models.ManyToManyField(blank=True, to='core.competency')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30, null=True)),
                ('project_subtitle', models.CharField(max_length=100, null=True)),
                ('project_image', models.URLField(blank=True, null=True)),
                ('project_category', models.CharField(choices=[('PM', 'Project Manager'), ('SD', 'Software Development'), ('EN', 'Entrepreneurship'), ('SU', 'Sustainability')], max_length=2)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('project_button_description', models.CharField(blank=True, max_length=50, null=True)),
                ('project_position', models.IntegerField(null=True)),
                ('show_or_hide', models.BooleanField(default=False)),
                ('project_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('project_technologies', models.ManyToManyField(blank=True, to='core.technologies')),
            ],
        ),
    ]
