# Generated by Django 4.0.6 on 2022-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_category',
        ),
        migrations.AddField(
            model_name='project',
            name='areas_of_expertise',
            field=models.ManyToManyField(blank=True, to='core.expertise'),
        ),
    ]
