# Generated by Django 4.0.6 on 2022-10-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
