# Generated by Django 4.0.6 on 2022-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_competency_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='proficiency',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
