# Generated by Django 4.0.6 on 2022-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_competency_proficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_button_description',
            new_name='button_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_executive',
            new_name='executive',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_technologies',
            new_name='technologies',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
    ]
