# Generated by Django 5.0.3 on 2025-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_extra_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='type',
            field=models.CharField(choices=[('aw', 'award'), ('ta', 'talk'), ('ce', 'certification'), ('pa', 'paper')], default='aw', max_length=2),
        ),
    ]
