version: '3.7'

services:

  web:
    build: .
    env_file: .env
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 500 guilsportfolio.wsgi:application
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./:/app
    expose:
      - 8000
    restart: unless-stopped
    network_mode: host
